const SCROLL_DURATION = 800;
const IN_VIEWPORT_DELAY_TIMER = 10;
const DIRECTION_HANDLE_DELAY_TIMER = 20;
const TRANSITION_TIMING_FUNCTION = "cubic-bezier(0.16, 1, 0.3, 1)";
const LOADING_TIMER = 300;
const OVERLAY_DURATION = 300;
const TOAST_SHOW_TIME = 3000;
const REPEAT_INTERVAL_TIMER = 5000;
const ONE_SECOND_TIMER = 1000;
const ONE_HUNDRED_MILISECOND_TIMER = 100;

const PAYMENT_REQUEST = "PAYMENT/PAYMENT_REQUEST";
const PAYMENT_SUCCESS = "PAYMENT/PAYMENT_SUCCESS";
const PAYMENT_FAIL = "PAYMENT/PAYMENT_FAIL";

export {
  SCROLL_DURATION,
  IN_VIEWPORT_DELAY_TIMER,
  DIRECTION_HANDLE_DELAY_TIMER,
  TRANSITION_TIMING_FUNCTION,
  LOADING_TIMER,
  OVERLAY_DURATION,
  TOAST_SHOW_TIME,
  REPEAT_INTERVAL_TIMER,
  ONE_SECOND_TIMER,
  ONE_HUNDRED_MILISECOND_TIMER,
  PAYMENT_REQUEST,
  PAYMENT_SUCCESS,
  PAYMENT_FAIL,
}